// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhYW_aAyyac9m-eNLrDacl1b3p4OHzM_I',
    appId: '1:525402002462:web:4acad42afdf3771115ca0f',
    messagingSenderId: '525402002462',
    projectId: 'combine-proj',
    authDomain: 'combine-proj.firebaseapp.com',
    storageBucket: 'combine-proj.appspot.com',
    measurementId: 'G-312N5SGRXL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2rv3-XBZIxTACwJTACATVnOuyrBuHGuY',
    appId: '1:525402002462:android:13c85f10cf4eebe715ca0f',
    messagingSenderId: '525402002462',
    projectId: 'combine-proj',
    storageBucket: 'combine-proj.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDW7OW0PhXD_jSOcldU5Zv7HHcuD8LfTkg',
    appId: '1:525402002462:ios:0117625a0194d00015ca0f',
    messagingSenderId: '525402002462',
    projectId: 'combine-proj',
    storageBucket: 'combine-proj.appspot.com',
    iosBundleId: 'com.example.combineProj',
  );
}
